# calling the important libraries

In [32]:
# importing libraries like google drive
# pandas
# matplotlib and seaborn
# numpy

import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import seaborn as sns

importing the google drive and uploading the file

In [33]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

if files are needed to be uploaded from local machines into colab then use

from google.colab import files

uploaded = files.upload()

In [34]:
cpx_combined = pd.read_excel('/content/drive/MyDrive/a dissertation methodoloy/Combined Datasets EPMA.xlsx',
                             sheet_name= 'cpx combined'
                             )

In [35]:
cpx_combined

,SAMPLE,NiO,F,CaO,SiO2,Cr2O3,Na2O,TiO2,V2O3,MnO,...,Lu,Hf,Ta,Pb,Th,U,C,M,R,T
0,KL2023-07-19-4_1,0.005,0.023,22.625,44.409,0.231,0.758,3.365,0.051,0.081,...,0.188,3.74,0.208,0.038,0.096,0.0176,1,0,0,3
1,KL2023-07-19-4_2,0.000,0.124,22.752,47.643,0.302,0.764,2.058,0.031,0.017,...,0.184,3.03,0.238,0.054,0.103,0.0157,0,1,0,3
2,KL2023-07-19-4_3,0.014,0.000,22.711,49.580,0.189,0.539,1.448,0.033,0.141,...,0.225,4.09,0.188,0.06,0.113,0.0135,0,0,1,3
3,KL2023-07-19-4_4,0.000,0.000,23.481,51.316,0.1,0.534,0.057,0.050,0.421,...,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0,3
4,KL2023-07-19-4_5,0.000,0.000,23.601,51.941,0.118,0.423,0.139,0.074,0.388,...,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,KL2023-07-25-8_43,0.000,0.000,23.304,47.393,0.026,0.748,1.640,0.018,0.106,...,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,2
414,KL2023-07-25-8_44,0.009,0.000,23.196,47.737,0.092,0.603,1.741,0.035,0.136,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,2
415,KL2023-07-25-8_45,0.011,0.098,23.203,46.864,0.031,0.646,1.915,0.045,0.100,...,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0,2
416,KL2023-07-25-8_46,0.018,0.000,23.210,45.340,0.071,0.644,2.295,0.077,0.067,...,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,2
417,KL2023-07-25-8_47,0.021,0.000,23.119,45.402,0.15,0.562,2.707,0.056,0.118,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,2

# reading the dataframe

to get the names of all columns and their index numbers

In [36]:
cpx_combined.columns

Index(['SAMPLE', 'NiO', 'F', 'CaO', 'SiO2', 'Cr2O3', 'Na2O', 'TiO2', 'V2O3',
       'MnO', 'MgO', 'ZnO', 'FeO', 'Al2O3', 'K2O', 'Li2O', 'Total with Li2O',
       'Total', 'Mg#', 'Li', 'Be', 'B', 'Mg', 'Si', 'Ca', 'Ca.1', 'Sc', 'Ti',
       'V', 'Cr', 'Mn', 'Co', 'Ni', 'Cu', 'Rb', 'Sr', 'Y', 'Zr', 'Nb', 'Cs',
       'Ba', 'La', 'Ce', 'Pr', 'Nd', 'Sm', 'Eu', 'Gd', 'Tb', 'Dy', 'Ho', 'Er',
       'Tm', 'Yb', 'Lu', 'Hf', 'Ta', 'Pb', 'Th', 'U', 'C', 'M', 'R', 'T'],
      dtype='object')

In [37]:
cpx_combined.index

RangeIndex(start=0, stop=418, step=1)

In [38]:
cpx_combined.head()

,SAMPLE,NiO,F,CaO,SiO2,Cr2O3,Na2O,TiO2,V2O3,MnO,...,Lu,Hf,Ta,Pb,Th,U,C,M,R,T
0,KL2023-07-19-4_1,0.005,0.023,22.625,44.409,0.231,0.758,3.365,0.051,0.081,...,0.188,3.74,0.208,0.038,0.096,0.0176,1,0,0,3
1,KL2023-07-19-4_2,0.000,0.124,22.752,47.643,0.302,0.764,2.058,0.031,0.017,...,0.184,3.03,0.238,0.054,0.103,0.0157,0,1,0,3
2,KL2023-07-19-4_3,0.014,0.000,22.711,49.580,0.189,0.539,1.448,0.033,0.141,...,0.225,4.09,0.188,0.06,0.113,0.0135,0,0,1,3
3,KL2023-07-19-4_4,0.000,0.000,23.481,51.316,0.1,0.534,0.057,0.050,0.421,...,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0,3
4,KL2023-07-19-4_5,0.000,0.000,23.601,51.941,0.118,0.423,0.139,0.074,0.388,...,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,3

In [39]:
cpx_combined.tail()

,SAMPLE,NiO,F,CaO,SiO2,Cr2O3,Na2O,TiO2,V2O3,MnO,...,Lu,Hf,Ta,Pb,Th,U,C,M,R,T
413,KL2023-07-25-8_43,0.000,0.000,23.304,47.393,0.026,0.748,1.640,0.018,0.106,...,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,2
414,KL2023-07-25-8_44,0.009,0.000,23.196,47.737,0.092,0.603,1.741,0.035,0.136,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,2
415,KL2023-07-25-8_45,0.011,0.098,23.203,46.864,0.031,0.646,1.915,0.045,0.100,...,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0,2
416,KL2023-07-25-8_46,0.018,0.000,23.210,45.340,0.071,0.644,2.295,0.077,0.067,...,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,2
417,KL2023-07-25-8_47,0.021,0.000,23.119,45.402,0.15,0.562,2.707,0.056,0.118,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,2

just to get quick statistical informationon all the numeric columns in cpx_combined dataframe. cpx_combined.describe() is used

In [40]:
cpx_combined.describe()

,NiO,F,CaO,SiO2,Na2O,TiO2,V2O3,MnO,MgO,ZnO,...,Yb,Lu,Hf,Ta,Th,U,C,M,R,T
count,418.000000,418.000000,418.000000,418.000000,418.000000,418.000000,418.000000,418.000000,418.000000,418.000000,...,118.000000,118.000000,118.000000,118.000000,118.000000,118.000000,418.000000,418.000000,418.000000,418.000000
mean,0.012352,0.019679,22.766269,46.557545,0.734468,2.241251,0.040758,0.128551,12.032939,0.019483,...,2.214949,0.311286,6.362034,0.866009,0.366905,0.056675,0.346890,0.311005,0.342105,1.794258
std,0.018414,0.038296,0.572686,2.171170,0.244873,0.694869,0.027708,0.071654,1.804440,0.030741,...,0.754055,0.122998,2.712326,0.890841,0.431334,0.073695,0.476551,0.463459,0.474983,0.720222
min,-0.007930,0.000000,20.626000,39.168000,0.226000,0.057000,0.000000,0.017000,5.911000,0.000000,...,0.661000,0.083700,1.470000,0.080800,0.026400,0.008300,0.000000,0.000000,0.000000,1.000000
25%,0.000000,0.000000,22.415250,45.284750,0.605000,1.787500,0.022000,0.085250,11.153525,0.000000,...,1.655000,0.218000,4.402500,0.291000,0.155000,0.025050,0.000000,0.000000,0.000000,1.000000
50%,0.000000,0.000000,22.792500,46.751000,0.663000,2.107500,0.042000,0.113946,12.348500,0.000000,...,2.220000,0.295500,6.005000,0.655000,0.258000,0.040350,0.000000,0.000000,0.000000,2.000000
75%,0.020750,0.022000,23.183250,48.089750,0.768750,2.632750,0.060000,0.150500,13.285750,0.033000,...,2.652500,0.377000,7.762500,1.086250,0.427000,0.064150,1.000000,1.000000,1.000000,2.000000
max,0.084000,0.223000,24.455000,51.973000,1.940000,4.350000,0.179000,0.587000,15.880000,0.156000,...,4.010000,0.638000,13.750000,5.180000,3.440000,0.720000,1.000000,1.000000,1.000000,3.000000

#Only selecting epma dataset

selecting epma dataset from cpx_combined dataframe for EDA, Visualization and preprocessing.

and naming it epma dataframe.

In [41]:
#to see only epma data

cpx_combined.iloc[:, 0 : 18]

# creating a new dataframe called epma

epma = cpx_combined.iloc[:, 0 : 19]

epma.dtypes

SAMPLE              object
NiO                float64
F                  float64
CaO                float64
SiO2               float64
Cr2O3               object
Na2O               float64
TiO2               float64
V2O3               float64
MnO                float64
MgO                float64
ZnO                float64
FeO                float64
Al2O3              float64
K2O                float64
Li2O               float64
Total with Li2O    float64
Total              float64
Mg#                float64
dtype: object

Only selecting relevant columns to check the statistical nature.
creating new dataframe by removing the first column sample.

In [42]:
epma

,SAMPLE,NiO,F,CaO,SiO2,Cr2O3,Na2O,TiO2,V2O3,MnO,MgO,ZnO,FeO,Al2O3,K2O,Li2O,Total with Li2O,Total,Mg#
0,KL2023-07-19-4_1,0.005,0.023,22.625,44.409,0.231,0.758,3.365,0.051,0.081,11.749,0.000,5.069,11.660,0.001,0.000,100.027,100.027,0.80247
1,KL2023-07-19-4_2,0.000,0.124,22.752,47.643,0.302,0.764,2.058,0.031,0.017,13.116,0.046,4.967,7.996,0.007,0.178,100.001,99.823,0.82759
2,KL2023-07-19-4_3,0.014,0.000,22.711,49.580,0.189,0.539,1.448,0.033,0.141,14.243,0.000,4.977,5.495,0.004,0.627,100.001,99.374,0.83158
3,KL2023-07-19-4_4,0.000,0.000,23.481,51.316,0.1,0.534,0.057,0.050,0.421,7.376,0.000,16.404,0.564,0.009,0.000,100.312,100.312,0.44330
4,KL2023-07-19-4_5,0.000,0.000,23.601,51.941,0.118,0.423,0.139,0.074,0.388,7.826,0.074,15.199,0.536,0.003,0.000,100.322,100.322,0.47872
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,KL2023-07-25-8_43,0.000,0.000,23.304,47.393,0.026,0.748,1.640,0.018,0.106,11.943,0.009,7.220,7.173,0.002,0.418,100.000,99.582,0.74157
414,KL2023-07-25-8_44,0.009,0.000,23.196,47.737,0.092,0.603,1.741,0.035,0.136,12.672,0.000,6.285,6.877,0.007,0.608,99.998,99.390,0.77778
415,KL2023-07-25-8_45,0.011,0.098,23.203,46.864,0.031,0.646,1.915,0.045,0.100,13.031,0.000,5.427,8.015,0.016,0.598,100.000,99.402,0.80899
416,KL2023-07-25-8_46,0.018,0.000,23.210,45.340,0.071,0.644,2.295,0.077,0.067,11.945,0.000,6.160,9.679,0.019,0.475,100.000,99.525,0.77647
417,KL2023-07-25-8_47,0.021,0.000,23.119,45.402,0.15,0.562,2.707,0.056,0.118,11.916,0.000,6.263,9.512,0.012,0.162,100.000,99.838,0.76744

In [43]:
epma_no_sample = epma.iloc[:,1:19] # creating new dataframe by removing the first column sample.
epma_no_sample.dtypes

NiO                float64
F                  float64
CaO                float64
SiO2               float64
Cr2O3               object
Na2O               float64
TiO2               float64
V2O3               float64
MnO                float64
MgO                float64
ZnO                float64
FeO                float64
Al2O3              float64
K2O                float64
Li2O               float64
Total with Li2O    float64
Total              float64
Mg#                float64
dtype: object

found that one column Cr2O3 has object dtype. which is unmatchable.

In [44]:
#checking the values of column Cr2O3

epma['Cr2O3']

0      0.231
1      0.302
2      0.189
3        0.1
4      0.118
       ...
413    0.026
414    0.092
415    0.031
416    0.071
417     0.15
Name: Cr2O3, Length: 418, dtype: object

#converting the object dtype of Cr2O3 into float.

In [45]:
'''
Ensuring All Values Are Strings Before Using .str: Convert the column to str before applying .str methods.
This prevents errors when dealing with mixed types (e.g., float, NaN, etc.).
'''
invalid_entries = epma[~epma['Cr2O3'].astype(str).str.replace('.', '', 1).str.isnumeric()]
print(invalid_entries)

# found negative oxide value percentage and string value CPX in Cr2O3.

                SAMPLE       NiO    F     CaO     SiO2    Cr2O3     Na2O  \
107  KL2023-07-23-3_34  0.000000  0.0  22.700  48.3940      CPX  0.58900
358  KL2023-07-25-7_29  0.015533  0.0  22.094  45.6748 -0.01734  1.00859

        TiO2   V2O3       MnO      MgO  ZnO      FeO   Al2O3       K2O   Li2O  \
107  1.78600  0.025  0.088000  13.8290  0.0  4.61300  7.5410  0.000000  0.291
358  1.81326  0.000  0.217395  10.1537  0.0  9.97681  7.9654  0.011418  0.000

     Total with Li2O      Total      Mg#
107        99.856000  99.565000  0.84444
358        98.913566  98.913566  0.64000

In [46]:
invalid_entries = epma[~epma['Cr2O3']
                                 .fillna('')  # Replace NaN with empty strings
                                 .astype(str)
                                 .str.replace('.', '', 1)
                                 .str.isnumeric()]
print(invalid_entries)

                SAMPLE       NiO    F     CaO     SiO2    Cr2O3     Na2O  \
107  KL2023-07-23-3_34  0.000000  0.0  22.700  48.3940      CPX  0.58900
358  KL2023-07-25-7_29  0.015533  0.0  22.094  45.6748 -0.01734  1.00859

        TiO2   V2O3       MnO      MgO  ZnO      FeO   Al2O3       K2O   Li2O  \
107  1.78600  0.025  0.088000  13.8290  0.0  4.61300  7.5410  0.000000  0.291
358  1.81326  0.000  0.217395  10.1537  0.0  9.97681  7.9654  0.011418  0.000

     Total with Li2O      Total      Mg#
107        99.856000  99.565000  0.84444
358        98.913566  98.913566  0.64000

In [47]:
print(epma['Cr2O3'].head())
print(epma['Cr2O3'].dtype)

0    0.231
1    0.302
2    0.189
3      0.1
4    0.118
Name: Cr2O3, dtype: object
object

In [48]:
'''
Replace non-numeric entries with a specific value:
'''
epma['Cr2O3'] = pd.to_numeric(epma['Cr2O3'], errors='coerce').fillna(0)  # Replace NaN with 0

In [49]:
epma['Cr2O3'].dtype

dtype('float64')

In [50]:
epma['Cr2O3'].min() # unexpected negative value.

-0.01734

#**chemical analysis of samples**

In [51]:
# Define typical clinopyroxene composition ranges
clinopyroxene_criteria = {
    'SiO2': (45, 55),  # SiO2 percentage
    'CaO': (20, 25),   # CaO percentage
    'MgO': (10, 20),   # MgO percentage
    'Na2O': (0, 2)     # Na2O percentage
}

# Check if MgO exists in the dataset
if 'MgO' in cpx_combined.columns:
    # Filter dataset based on clinopyroxene criteria
    clinopyroxene_samples = cpx_combined[
        (cpx_combined['SiO2'] >= clinopyroxene_criteria['SiO2'][0]) &
        (cpx_combined['SiO2'] <= clinopyroxene_criteria['SiO2'][1]) &
        (cpx_combined['CaO'] >= clinopyroxene_criteria['CaO'][0]) &
        (cpx_combined['CaO'] <= clinopyroxene_criteria['CaO'][1]) &
        (cpx_combined['Na2O'] >= clinopyroxene_criteria['Na2O'][0]) &
        (cpx_combined['Na2O'] <= clinopyroxene_criteria['Na2O'][1]) &
        (cpx_combined['MgO'] >= clinopyroxene_criteria['MgO'][0]) &
        (cpx_combined['MgO'] <= clinopyroxene_criteria['MgO'][1])
    ]

    # Count the number of samples matching the criteria
    clinopyroxene_sample_count = clinopyroxene_samples.shape[0]
else:
    clinopyroxene_sample_count = "MgO column is missing in the dataset."

clinopyroxene_sample_count

311

In [52]:
# Define typical olivine composition ranges
olivine_criteria = {
    'SiO2': (35, 45),  # SiO2 percentage
    'MgO': (40, 50),   # MgO percentage
    'CaO': (0, 0.05),  # CaO percentage
    'Na2O': (0, 0.05)  # Na2O percentage
}

# Check if the required columns exist in the dataset
required_columns = ['SiO2', 'MgO', 'CaO', 'Na2O']
missing_columns = [col for col in required_columns if col not in cpx_combined.columns]

if not missing_columns:
    # Filter dataset based on olivine criteria
    olivine_samples = cpx_combined[
        (cpx_combined['SiO2'] >= olivine_criteria['SiO2'][0]) &
        (cpx_combined['SiO2'] <= olivine_criteria['SiO2'][1]) &
        (cpx_combined['MgO'] >= olivine_criteria['MgO'][0]) &
        (cpx_combined['MgO'] <= olivine_criteria['MgO'][1]) &
        (cpx_combined['CaO'] >= olivine_criteria['CaO'][0]) &
        (cpx_combined['CaO'] <= olivine_criteria['CaO'][1]) &
        (cpx_combined['Na2O'] >= olivine_criteria['Na2O'][0]) &
        (cpx_combined['Na2O'] <= olivine_criteria['Na2O'][1])
    ]

    # Count the number of samples matching the criteria
    olivine_sample_count = olivine_samples.shape[0]
else:
    olivine_sample_count = f"The dataset is missing the following columns: {', '.join(missing_columns)}"

olivine_sample_count

0

In [53]:
# Define typical amphibole composition ranges
amphibole_criteria = {
    'SiO2': (40, 60),       # SiO2 percentage
    'MgO': (10, 25),        # MgO percentage
    'CaO': (9, 15),         # CaO percentage
    'Na2O': (0.5, 5),       # Na2O percentage
    'Al2O3': (5, 15)        # Al2O3 percentage
}

# Check if the required columns exist in the dataset
required_columns_amphibole = ['SiO2', 'MgO', 'CaO', 'Na2O', 'Al2O3']
missing_columns_amphibole = [col for col in required_columns_amphibole if col not in cpx_combined.columns]

if not missing_columns_amphibole:
    # Filter dataset based on amphibole criteria
    amphibole_samples = cpx_combined[
        (cpx_combined['SiO2'] >= amphibole_criteria['SiO2'][0]) &
        (cpx_combined['SiO2'] <= amphibole_criteria['SiO2'][1]) &
        (cpx_combined['MgO'] >= amphibole_criteria['MgO'][0]) &
        (cpx_combined['MgO'] <= amphibole_criteria['MgO'][1]) &
        (cpx_combined['CaO'] >= amphibole_criteria['CaO'][0]) &
        (cpx_combined['CaO'] <= amphibole_criteria['CaO'][1]) &
        (cpx_combined['Na2O'] >= amphibole_criteria['Na2O'][0]) &
        (cpx_combined['Na2O'] <= amphibole_criteria['Na2O'][1]) &
        (cpx_combined['Al2O3'] >= amphibole_criteria['Al2O3'][0]) &
        (cpx_combined['Al2O3'] <= amphibole_criteria['Al2O3'][1])
    ]

    # Count the number of samples matching the criteria
    amphibole_sample_count = amphibole_samples.shape[0]
else:
    amphibole_sample_count = f"The dataset is missing the following columns: {', '.join(missing_columns_amphibole)}"

amphibole_sample_count

0

In [54]:
# Define typical plagioclase composition ranges
plagioclase_criteria = {
    'SiO2': (50, 60),       # SiO2 percentage
    'Al2O3': (20, 30),      # Al2O3 percentage
    'CaO': (5, 15),         # CaO percentage
    'Na2O': (4, 12),        # Na2O percentage
    'K2O': (0, 2)           # K2O percentage
}

# Check if the required columns exist in the dataset
required_columns_plagioclase = ['SiO2', 'Al2O3', 'CaO', 'Na2O', 'K2O']
missing_columns_plagioclase = [col for col in required_columns_plagioclase if col not in cpx_combined.columns]

if not missing_columns_plagioclase:
    # Filter dataset based on plagioclase criteria
    plagioclase_samples = cpx_combined[
        (cpx_combined['SiO2'] >= plagioclase_criteria['SiO2'][0]) &
        (cpx_combined['SiO2'] <= plagioclase_criteria['SiO2'][1]) &
        (cpx_combined['Al2O3'] >= plagioclase_criteria['Al2O3'][0]) &
        (cpx_combined['Al2O3'] <= plagioclase_criteria['Al2O3'][1]) &
        (cpx_combined['CaO'] >= plagioclase_criteria['CaO'][0]) &
        (cpx_combined['CaO'] <= plagioclase_criteria['CaO'][1]) &
        (cpx_combined['Na2O'] >= plagioclase_criteria['Na2O'][0]) &
        (cpx_combined['Na2O'] <= plagioclase_criteria['Na2O'][1]) &
        (cpx_combined['K2O'] >= plagioclase_criteria['K2O'][0]) &
        (cpx_combined['K2O'] <= plagioclase_criteria['K2O'][1])
    ]

    # Count the number of samples matching the criteria
    plagioclase_sample_count = plagioclase_samples.shape[0]
else:
    plagioclase_sample_count = f"The dataset is missing the following columns: {', '.join(missing_columns_plagioclase)}"

plagioclase_sample_count

0